<?php

namespace App\Models;

use App\Scopes\AnggotaScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Anggota extends Model
{
    use SoftDeletes;

    protected $table = "users";
    protected $primaryKey = "id";

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new AnggotaScope(1));
    }
    protected $hidden = [
        'password', 'remember_token',
    ];
}
