<?php

namespace App\Models;

use App\Scopes\PengabdianScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Pengabdian extends Model
{
    protected $table = "penelitian";

    protected $primaryKey = "penelitian_id";

    use SoftDeletes;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new PengabdianScope);
    }

    public function status()
    {
        return $this->belongsTo(SurveyStatus::class,'ss_id', 'ss_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class,'user_id', 'id');
    }

    public function files()
    {
        return $this->hasMany(FileModel::class, $this->primaryKey);
    }
}
