<?php

namespace App\Models;

use App\Scopes\SurveyScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Survey extends Model
{
    use SoftDeletes;

    protected $table = "surveys";

    protected $primaryKey = "survey_id";

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new SurveyScope());
    }

    public function status()
    {
        return $this->belongsTo(SurveyStatus::class, 'ss_id', 'ss_id');
    }
}
